### ISSUE TITLE
ERROR in step 9 "python3 setup.py bdist_wheel"

### ISSUE THREAD

**Issue by rusty-error** [superuser789/MediaPipe-on-RaspberryPi#11]
I completed all 8 steps but when i try to complete this one i get an error. How to solve this? Thanks.

```
running bdist_wheel
running build
running build_binary_graphs
generating binarypb: mediapipe/modules/face_detection/face_detection_short_range_cpu
Starting local Bazel server and connecting to it...
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Traceback (most recent call last):
	File "/home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl", line 16, column 76, in <toplevel>
		load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
ERROR: While resolving toolchains for target //mediapipe/modules/face_detection:face_detection_short_range_cpu: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
ERROR: Analysis of target '//mediapipe/modules/face_detection:face_detection_short_range_cpu' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
INFO: Elapsed time: 16.737s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets conf\
igured)
```

**Comment by ccarmatic** [comment]
```
ERROR: Traceback (most recent call last):
        File "/home/carmatic/.cache/bazel/_bazel_carmatic/22db4830a61cb727947872a826b3fd8a/external/rules_cc/cc/private/rules_impl/compiler_flag.bzl", line 17, column 76, in <toplevel>
                load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
ERROR: While resolving toolchains for target //mediapipe/modules/face_detection:face_detection_short_range_cpu: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/carmatic/.cache/bazel/_bazel_carmatic/22db4830a61cb727947872a826b3fd8a/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/compiler_flag.bzl' has errors
ERROR: Analysis of target '//mediapipe/modules/face_detection:face_detection_short_range_cpu' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/carmatic/.cache/bazel/_bazel_carmatic/22db4830a61cb727947872a826b3fd8a/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/compiler_flag.bzl' has errors
```

**Comment by Jay042003** [comment]
DEBUG: Repository rules_cc instantiated at:
  /home/pi/mediapipe-0.8.8/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Traceback (most recent call last):
	File "/home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/rules_cc/cc/private/rules_impl/compiler_flag.bzl", line 17, column 76, in <toplevel>
		load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain", "use_cpp_toolchain")
Error: file '@bazel_tools//tools/cpp:toolchain_utils.bzl' does not contain symbol 'use_cpp_toolchain' (did you mean 'find_cpp_toolchain'?)
ERROR: While resolving toolchains for target //mediapipe/modules/face_detection:face_detection_short_range_cpu: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/compiler_flag.bzl' has errors
ERROR: Analysis of target '//mediapipe/modules/face_detection:face_detection_short_range_cpu' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/pi/.cache/bazel/_bazel_pi/a69eb3bf972519b4a5715566543279ba/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/compiler_flag.bzl' has errors
INFO: Elapsed time: 116.639s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
