### ISSUE TITLE
Import error in mediapipe-rpi4

### ISSUE THREAD

**Issue by Shubhs0411** [superuser789/MediaPipe-on-RaspberryPi#9]
Error occurred while importing mediapipe library. 
Python==3.9.2 , mediapipe-rpi4==0.8.8 
Traceback (most recent call last):
  File "/home/pi/Desktop/ifm/Pose_Application.py", line 10, in <module>
    import mediapipe as mp 
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.9/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

**Comment by dhanushnayak** [comment]
facing same issue

**Comment by NowLoadY** [comment]
same

**Comment by wicoben** [comment]
Have you solved the problem,Could you tell me how to solve it?

**Comment by NowLoadY** [comment]
> Have you solved the problem,Could you tell me how to solve it?

Ricso's solution,  have you tried?

https://github.com/superuser789/MediaPipe-on-RaspberryPi/issues/10#issuecomment-1312527982

**Comment by mcwhorpj** [comment]
> > Have you solved the problem,Could you tell me how to solve it?
> 
> Ricso's solution, have you tried?
> 
> [#10 (comment)](https://github.com/superuser789/MediaPipe-on-RaspberryPi/issues/10#issuecomment-1312527982)

I am still having difficulty. When I do NowLoadY suggested method, followed by Risco's added suggestion (both from the link above), I am indeed able to install mediapipe on the Raspberry Pi 4 running either 32 bit or 64 bit version of Bullseye. The issue is, during the mediapipe installation, it upgrades my opencv from 4.5.1 to 4.6.0. The new version of opencv which is installed is NOT enabled for gstreamer, hence you can not use the Raspberry Pi camera in opencv any more. So, the goal of having mediapipe running on Bullseye and having use of the Raspberry Pi camera remains an illusive goal. Any help would be greatly appreciated.
Paul McWhorter
